### ISSUE TITLE
想加入

### ISSUE THREAD

**Issue by fuzhiyong2** [TIDC/toy-redis#2]
之前也看sylar的课，学了一半。想继续学习下。你还有什么功能没在这版源码里添加的？我想加入一起写一两个功能类。

**Comment by zjlian** [comment]
toy-redis 这个项目现在才起步，我们还在探索适合的代码架构和方案，后续很可能会频繁大规模重构，所以目前还不太适合加人捏😘

**Comment by fuzhiyong2** [comment]
好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月23日(周六) 晚上8:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TIDC/toy-redis] 想加入 (Issue #2)




 
toy-redis 这个项目现在才起步，我们还在探索适合的代码架构和方案，后续很可能会频繁大规模重构，所以目前还不太适合加人捏😘
